### ISSUE TITLE
add quick sort algorithm

### ISSUE THREAD

**Issue by bhimeshagrawal** [AkashMittal-30/Cpp-Algorithms#3]

**Comment by bhimeshagrawal** [comment]
Hey @AkashMittal-30 , Can I work on this issue. Please assign me

**Comment by singhankur101** [comment]
please assign me this issue i want to work on this issue

**Comment by seema-Patel888** [comment]
hello @AkashMittal-30 , I would like to contribute to this issue.

**Comment by LikhithaTadikonda** [comment]
I would like to contribute
