### ISSUE TITLE
Add binary search algorithm

### ISSUE THREAD

**Issue by anurag-crypto** [AkashMittal-30/Cpp-Algorithms#4]

**Comment by anurag-crypto** [comment]
Hey @AkashMittal-30 , can I work on this issue? Please assign it to me.

**Comment by shiv0403** [comment]
Please assign this issue to me @AkashMittal-30

**Comment by seema-Patel888** [comment]
hello @AkashMittal-30 , I would like to contribute to the issue.

**Comment by LikhithaTadikonda** [comment]
Hey I can contribute to this with BST with all operations in cpp :)
