### ISSUE TITLE
Add Linear search in between indexes

### ISSUE THREAD

**Issue by AkashMittal-30** [AkashMittal-30/Cpp-Algorithms#5]
Add a function to search from a given index to another given index in the array and return its index if it's present else return -1.

**Comment by prajakta2809** [comment]
Can you assign this to me as I am good at DSA.

**Comment by singhankur101** [comment]
Can you please assign me this because i am doing cp from last 2 year also i have a decent score on Codechef and Codeforces and solved 200+ que on gfg

**Comment by AkashMittal-30** [comment]
sure!!

**Comment by prajakta2809** [comment]
can you add label hacktoberfest accepted label.
