### ISSUE TITLE
Add Segment tree with lazy propagation

### ISSUE THREAD

**Issue by shiv0403** [AkashMittal-30/Cpp-Algorithms#7]

**Comment by shiv0403** [comment]
@AkashMittal-30 can you assign this issue to me ?

**Comment by AkashMittal-30** [comment]
Yeah Sure!!

**Comment by shiv0403** [comment]
I have made the PR @AkashMittal-30. Please check it

**Comment by shiv0403** [comment]
Added a folder and updated request.txt

**Comment by AkashMittal-30** [comment]
Nicely done, Good work!!
